# Generated by Django 3.0.7 on 2020-06-12 13:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rallypally', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='receivedmessage',
            old_name='twilio_number_sid',
            new_name='twilio_number',
        ),
    ]
